// Assignment Code

// Creating global variables to store the pool from which the password is generated.
var generateBtn = document.querySelector("#generate");
var lowercaseLetters = "abcdefghijklmnopqrstuvwxyz";
var uppercaseLetters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
var specialCharacters = " !\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~";
var numerals = "0123456789";
var passwordpool = "";

// Write password to the #password input
function writePassword() {

  var characterselect = false; 
// created a while loop to collect user selection on character types
  while (!characterselect) {
    var isUseLowerCase = confirm("Would you like to have lower case letters in your password? Hit cancel if your answer is 'no'.");
    if (isUseLowerCase){
     passwordpool = passwordpool + lowercaseLetters;
    };
    // console.log("islowercase test: " + passwordpool);
    var isUseUpperCase = confirm("Would you like to have upper case letters in your password? Hit cancel if your answer is 'no'.");
    if(isUseUpperCase) {
      passwordpool = passwordpool + uppercaseLetters;
    };
    // console.log("isUppercase test: " + passwordpool);
    var isNumerals = confirm("Would you like to have numbers in your password? Hit cancel if your answer is 'no'.");
    if(isNumerals) {
      passwordpool = passwordpool + numerals;
    };
    // console.log("Numerals test: " + passwordpool);
    var isSpecialCharacters = confirm("Would you like to have Special Characters in your password? Hit cancel if your answer is 'no'.");
    if(isSpecialCharacters) {
      passwordpool = passwordpool + specialCharacters;
    };
    // console.log("Special characters test: " + passwordpool);

    // test to make sure the user selected any character types
    if (passwordpool === "") {
      alert("You must choose at least one character type to generate a password.")
      characterselect = false;
    }
    else {
      characterselect = true;
    }
  }
    
  alert("You have selected the following character types for your password:\nLowercase: " + isUseLowerCase + "\nUppercase: " + isUseUpperCase + "\nNumerals: " + isNumerals + "\nSpecial Characters: " + isSpecialCharacters); 

//   generating the legnth of the password
  var numOfChar = Number(prompt("How long would you like your password to be?\n Password must be at least 8 characters long and no more than 128.\n"));
//   console.log("Number of characters: " + numOfChar);
  if (isNaN(numOfChar) || numOfChar<8 || numOfChar>128) {
    correctRange = false;
    while(!correctRange) {
      alert("You have selected a value outside of acceptable range.")
      numOfChar = Number(prompt("How long would you like your password to be?\n Password must be at least 8 characters long and no more than 128.\n"));
      if (isNaN(numOfChar)||numOfChar<8||numOfChar>128) {
        correctRange = false;
      }
      else {
        correctRange = true;
      }
    }
  }
// randomly selecting characters from the pool generated by user
  function generatePassword() {
    var passwordstring = "";
    for (var i = 0; i < numOfChar; i++) {
      var j = Math.floor(Math.random() * (passwordpool.length -1));
      console.log(j)
      passwordstring = passwordstring + passwordpool[j];
    }
  return passwordstring;
  }
  var password = generatePassword();
//   resetting password pool so you can do it again
  passwordpool = "";
  var passwordText = document.querySelector("#password");
  passwordText.value = password;

};




// Add event listener to generate button
generateBtn.addEventListener("click", writePassword);